tap "felixkratz/formulae"

brew "bat"
brew "cloudflared"
brew "colima"
brew "eza"
brew "fd"
brew "felixkratz/formulae/borders"
brew "felixkratz/formulae/sketchybar"
brew "fish"
brew "fontconfig"
brew "fzf"
brew "glow"
brew "jaq", args: ["HEAD"]
brew "mise"
brew "neovim"
brew "opencode"
brew "ripgrep"
brew "uv"

cask "bruno"
cask "cmux"
cask "flameshot"
cask "font-jetbrains-mono-nerd-font"