tap "felixkratz/formulae"

brew "bat"
brew "cloudflared"
brew "colima"
brew "eza"
brew "fd"
brew "felixkratz/formulae/borders"
brew "felixkratz/formulae/sketchybar"
brew "fnm"
brew "fontconfig"
brew "fzf"
brew "glow"
brew "jaq", args: ["HEAD"]
brew "jq"
brew "lazygit"
brew "mise"
brew "neovim"
brew "opencode"
brew "ripgrep"
brew "starship"
brew "tmux"
brew "uv"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

cask "bruno"
cask "cmux"
cask "flameshot"
cask "font-jetbrains-mono-nerd-font"
